[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
near-api = "0.3.0"
near-crypto = "0.27.0"
near-primitives = "0.27.0"
serde_json = "1.0.133"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"